server:
  port: 8090
spring:
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    com:
      example: trace
